# Generated by Django 5.1.2 on 2024-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_completedtaskhistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('low', 'Low Priority (Complete within a month)'), ('medium', 'Moderate Priority (Complete within two weeks)'), ('Urgent', 'High Priority (Complete within a few days)')], default='low', max_length=10),
        ),
    ]
